### PR TITLE
Fix BuildProperties

### LINKED ISSUE #134: BuildProperties needs a way to close a stream it opens
https://github.com/paypal/cascade/blob/develop/common/src/main/scala/com/paypal/cascade/common/properties/BuildProperties.scala#L38

### PR DESCRIPTION
**Pull request by 2rs2ts**
* Fixes #134 by using the primitive `try`/`finally` construct
* Fixes another bug where a `Some(null)` could be created. Please don't use `.toOption`.
* Lets `BuildProperties` be constructed with a different resource path in case downstream users have different project structures. Bonus effect: made it much easier to test.
* Oh, by the way, the test for this class actually tests something now instead of just making itself pass with Mockito. While the sweet minty taste is compelling, we do have to actually test the code.
* Other cleanup.

### CODE REVIEW

File: common/src/main/scala/com/paypal/cascade/common/properties/BuildProperties.scala [hunk 1]
```diff
@@ -15,35 +15,41 @@
...
-      p.load(stream)
-      p
+    Option(getClass.getResource(propertiesResourcePath)).flatMap { url =>
+      try {
+        val stream = url.openStream()
+        val p = new Properties
+        try {
+          p.load(stream)
+          Some(p)
+        } finally {
```
Comment (kionka) [inline common/src/main/scala/com/paypal/cascade/common/properties/BuildProperties.scala]: Nested ```try```s are kinda sad, though "more correct". Scala's ```Try``` should be sufficient for most of our use cases. Just a thought.

**Comment by kionka** [comment]
Much better. :shipit:

File: common/src/main/scala/com/paypal/cascade/common/properties/BuildProperties.scala [hunk 2]
```diff
@@ -15,35 +15,41 @@
...
-    } yield {
-      p.load(stream)
-      p
+    Option(getClass.getResource(propertiesResourcePath)).flatMap { url =>
+      try {
+        val stream = url.openStream()
+        val p = new Properties
+        try {
+          p.load(stream)
+          Some(p)
```
Comment (kionka) [inline common/src/main/scala/com/paypal/cascade/common/properties/BuildProperties.scala]: I guess I'll be pedantic here and say this should be an ```Option```.

File: common/src/main/scala/com/paypal/cascade/common/properties/BuildProperties.scala (hunk 1 above)
Comment (2rs2ts) [inline common/src/main/scala/com/paypal/cascade/common/properties/BuildProperties.scala]: It's just my personal opinion that all resources should be closed in a `finally` and `scala.util.Try` just doesn't offer that functionality. I could have made the outer block a `Try` but if I'm using one primitive I might as well use two.
